gitea:
  repositories_path: "Your project root path on your local machine/dependencies/gitea/git/repositories"

elasticsearch:
  urls:
    - "http://localhost:9200"
  index_ngram: "handled_n_grams"
  index_handled_commits: "handled_commits"

mysql:
  host: "127.0.0.1"
  port: 3307
  username: "gitea"
  password: "gitea"
  database: "gitea"

rabbitmq:
  host: "127.0.0.1"
  port: 5672

service:
  lang_suffix:
    - "java"
  mit: 50
  mil: 6
  ngram: 5
  filter_threshold: 10
  verify_threshold: 70

coldstart_service:
  THREADNUM: 2

incremental_service:
  THREADNUM: 2

nil:
  basepath: "Your project root path on your local machine/parser/nil"
  rel_func_extractor_path: "Func-extractor-LSICCDS.jar"

client_service:
  gitea_url: "Your address for gitea service"
  token: "Your personal account token who installed the webhook client service"
